/**
 *
 * $Id$
 */
package org.talend.core.model.metadata.builder.connection.validation;

/**
 * A sample validator interface for {@link org.talend.core.model.metadata.builder.connection.BigQueryConnection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BigQueryConnectionValidator {

    boolean validate();

    boolean validateAccessToken(String value);

    boolean validateServiceAccountCredentialsFile(String value);

    boolean validateClientId(String value);

    boolean validateClientSecret(String value);

    boolean validateAuthorizationCode(String value);

    boolean validateProjectId(String value);

    boolean validateUseRegionEndpoint(boolean value);

    boolean validateRegionEndpoint(String value);

    boolean validateTokenFilePath(String value);

    boolean validateAuthMode(String value);
}
